### ISSUE TITLE
Issue running 'make' in 'multiprocessing' on MacOS 13.4

### ISSUE THREAD

**Issue by dbl001** [wmayner/pyphi#106]
```
% pip show pyphi   
Name: pyphi
Version: 1.2.0
Summary: Python library for computing integrated information.
Home-page: http://github.com/wmayner/pyphi
Author: William GP Mayner
Author-email: wmayner@gmail.com
License: GNU General Public License v3.0
Location: /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages
Requires: decorator, joblib, numpy, psutil, pyemd, pymongo, pyyaml, redis, scipy, tblib, tqdm
Required-by: 
```
% make
```
test/test_parallel.py::test_config_persists_through_paralellization FAILED [ 70%]


    def test_config_persists_through_paralellization():
        new_config_value = "foobar"
>       with config.override(WELCOME_OFF=new_config_value):

test/test_parallel.py:93: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pyphi/conf.py:329: in __enter__
    self.conf.load_dict(self.new_values)
pyphi/conf.py:282: in load_dict
    setattr(self, k, v)
pyphi/conf.py:263: in __setattr__
    super().__setattr__(name, value)
pyphi/conf.py:209: in __set__
    self._validate(value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pyphi.conf.Option object at 0x7fb7684f1fa0>, value = 'foobar'

    def _validate(self, value):
        """Validate the new value."""
        if self.type is not None and not isinstance(value, self.type):
>           raise ValueError(
                "{} must be of type {} for {}; got {}".format(
                    value, self.type, self.name, type(value)
                )
            )
E           ValueError: foobar must be of type <class 'bool'> for WELCOME_OFF; got <class 'str'>

pyphi/conf.py:216: ValueError
------------------------------ Captured log setup ------------------------------
INFO     pyphi.test:conftest.py:141 Flushing caches...
--------------------------- Captured stdout teardown ---------------------------

--------------------------- Captured stderr teardown ---------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory

```

**Comment by dbl001** [comment]
error： _multiprocessing.SemLock( FileNotFoundError: [Errno 2] No such file or directory #33 
https://github.com/gramineproject/examples/issues/33
